### ISSUE TITLE
Can't show keyboard on iPad

### ISSUE THREAD

**Issue by rgamage** [downforacross/downforacross.com#192]
Sorry, I'm new here, but I can't figure out how to show the keyboard when using the site on an iPad.  I can select squares, but cannot enter any text, because there is no keyboard.  Is there some hidden feature to show a keyboard / enter text?

**Comment by jonycgn** [comment]
Issue #196 may be related. Perhaps worth trying if the problem is still there now?

**Comment by rgamage** [comment]
Tried again, still no keyboard appears anywhere when viewing the crossword.  Shouldn't the on-screen keyboard pop up when you touch a square?  I can't see any way to enter any text at all.

**Comment by stevenhao** [comment]
Could you go to https://www.whatismybrowser.com/detect/what-is-my-user-agent and let me know what your user-agent string is? It sounds like you may be using an iPad that self-reports as a desktop computer instead of a tablet. 

You may also want to try finding a button that allows you to "request mobile site".

**Comment by rgamage** [comment]
My user agent is below. I don't see any way to switch to the mobile site.
Your User Agent is:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15
(KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
<https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes>

**Comment by jonycgn** [comment]
@rgamage you can request the mobile site by tapping on the two "A"s in the left corner of the address bar.

**Comment by rgamage** [comment]
Thank you so much, this works.  I can now type in the squares, and see one
clue at a time.  I can't see a list of the clues, so that's kind of a drag,
but I think there is already an issue open on that.

Randy

**Comment by electroly** [comment]
This is an issue that is still relevant today (July 2023). On an iPad you have two choices:

- In desktop mode, the keyboard doesn't appear so you can't type anything.
- In mobile mode, the keyboard appears, but the site hides all the clues.

Hiding the clues in mobile mode makes sense for a phone but on an iPad, desktop mode is the desired layout since there is plenty of room to show the clues. But only mobile mode is functional. We're stuck using the mobile phone interface on a large iPad screen.

**Comment by flackr** [comment]
Having mobile be a separate mode with separate code is I think not very scalable. There are always systems which are counter to being either a phone sized mobille device or a large screen desktop, e.g.
* Users can play in a small window on a desktop where the "mobile" sized UI could be helpful
* Users could be playing on a tablet (large screen) with or without an attached keyboard.
* Users could be playing on a "desktop" without a keyboard, e.g. a detached surfacebook or flipped chromebook.

I would suggest that:
* Layout changes, such as hiding the clues by default, be based on available screen space.
* Click events on the grid should always focus an invisible input element. The system will know whether to show a virtual keyboard in response in all of the scenarios outlined above (i.e. in desktop or mobile).

**Comment by flackr** [comment]
I've been playing with the PR I linked for a while and it's working great both on mobile and desktop using the same full view. If anyone else wants to try it you can load the preview URL: https://vercel.live/open-feedback/downforacrosscom-git-fork-flackr-show-vk-ca06c0-downforacross1.vercel.app?via=pr-comment-visit-preview-link&passThrough=1

I think longer term having a separate MobileGridControls class could be deprecated and the mode switching changed in favour of screen size based switching.
