### ISSUE TITLE
Copyright symbol not being properly rendered

### ISSUE THREAD

**Issue by TMiguelT** [downforacross/downforacross.com#90]
I have a `.puz` file that has the symbol © in the copyright line (as it should), but this is being rendered as "â©". For example: https://downforacross.com/beta/game/209928-splob. 

Some quick googling suggests that you need to add a meta charset tag: https://stackoverflow.com/a/17493693/2148718.

**Comment by stevenhao** [comment]
Thanks for raising this, it's an interesting issue. I'm trying out the `<meta charset="UTF-8">` solution here: https://github.com/downforacross/downforacross.com/pull/91, but it doesn't seem to address issue. Example: https://downforacrosscom-git-fix-puz-encoding.downforacross1.now.sh/beta/game/209928-splob
![image](https://user-images.githubusercontent.com/1988030/80321747-6b39fb80-87d4-11ea-9a52-ffaac1840503.png)


I believe the problem is with encoding / decoding strings from the puz file format: https://github.com/downforacross/puzjs/blob/fcf0b564d86e74b90aaf7daf056282a4ad55d361/src/puz.js#L15; as written I believe it only supports ASCII, whereas it needs to support Unicode too

**Comment by stevenhao** [comment]
Sorry, the more relevant part of the `puzjs` source to link to is its decoding, not encoding. Encoding actually seems to be correct-ish.

https://github.com/downforacross/puzjs/blob/fcf0b564d86e74b90aaf7daf056282a4ad55d361/src/puz.js#L402

**Comment by stevenhao** [comment]
Found the issue; turns out it lies in neither downforacross nor puzjs. Rather, the file was generated incorrectly (due to a tricky bug). See this comment: https://github.com/downforacross/downloadacross/pull/14#issuecomment-619642767
